### ISSUE TITLE
Is a UI also supposed to be generated?

### ISSUE THREAD

**Issue by varunachar** [tjwebb/sails-swagger#11]
I'm currently only seeing a JSON text when browsing to /swagger/doc. Is a UI also supposed to be generated?

**Comment by praveenaj** [comment]
This only generates the swagger spec in JSON. You will have to download the [swagger-ui](https://github.com/swagger-api/swagger-ui) and point it to http://localhost:1337/swagger/doc

**Comment by tjwebb** [comment]
You can also use http://swagger.balderdash.io
