### ISSUE TITLE
Sails-swagger generates useless/strange routes

### ISSUE THREAD

**Issue by adrien-candiotti** [tjwebb/sails-swagger#19]
With a simple account model swagger-sails generate stuff like:

DELETE /account/find/{id}
GET /account/find/{id}
PATCH /account/find/{id}
POST /account/find/{id}
PUT /account/find/{id}

Is it a normal behaviour?

**Comment by AlexisNo** [comment]
Yes, it is the normal behavior of "actions" blueprints http://sailsjs.org/documentation/anatomy/my-app/config/blueprints-js

**Comment by gustperz** [comment]
in my case is generating the POST /model/{id} route, which does not really exist
