### ISSUE TITLE
Can I omit routes/controllers and models not created in my server?

### ISSUE THREAD

**Issue by talamaska** [tjwebb/sails-swagger#21]
Currently I see there are Models that aren't present in my server like Group and Contact.
The controllers are missing in 0.5.1, but that's not the point.
I don't want to see those models and controllers, they should be just for testing purposes.
Could you please assist somehow?

**Comment by Tronix117** [comment]
Same here

**Comment by Tronix117** [comment]
Same here, but there is a temporary fix, in your `config/swagger.js` file, use the following:

``` javascript
module.exports.swagger = {
  pkg: require('../package')
  marlinspike: {
    models: false
  }
}
```

**Comment by talamaska** [comment]
thanks

**Comment by lahaxearnaud** [comment]
Api is not available any more but in swagger Contact / Group are still available.
