### ISSUE TITLE
Test models creating database tables

### ISSUE THREAD

**Issue by RyanParsley** [tjwebb/sails-swagger#27]
Judging by the commit message of "move test models into local project" found here: https://github.com/tjwebb/sails-swagger/tree/v0.5.1/api/models, it looks like the "group" and "contact" tables being created in my database are not necessary. Is there configuration that I'm not aware of to skip these (other than changing the "alter" option to "safe")?

**Comment by gggordon** [comment]
Hi @RyanParsley , according to the documentation for [Waterline ORM](http://sailsjs.org/documentation/concepts/models-and-orm/model-settings) being used, you are on the right path. Specifying

```
migrate:'safe'
```

in the **group** and **contact** models should prevent this.

I cannot test this proposal right now, but will do it later. Did you change the **migrate** _alter_ to _safe_ in your _config/models.js_ or did you try the above?
